import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'

const telkaRegular = localFont({
	src: './fonts/TelkaTRIAL-Extended-Regular.woff',
	variable: '--font-telka-regular',
	weight: '100 300 900'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="font-main antialiased">
				<div className="flex min-h-screen w-full flex-col">{children}</div>
			</body>
		</html>
	)
}
